### PR TITLE
Update to SMCC 2.1.1.3 + targets support

### PR DESCRIPTION
**Pull request by screamerbg**
Test results pending...

### CODE REVIEW

**Comment by screamerbg** [comment]
Results part 1:
```
2019-02-20 15:25:17 TEST SUMMARY PER TARGET:
+---------------+-------------------------------------------------+---------+--------+
| target        | test suite                                      | result  |   time |
+---------------+-------------------------------------------------+---------+--------+
| DISCO_F469NI  | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  87.65 |
| DISCO_F469NI  | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      | 246.78 |
| NUCLEO_F412ZG | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      |  93.33 |
| NUCLEO_F412ZG | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      | 261.36 |
| NUCLEO_L476RG | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      | 188.69 |
| NUCLEO_L476RG | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      | 374.23 |
| NUCLEO_L4R5ZI | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK      | 120.49 |
| NUCLEO_L4R5ZI | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK      | 310.32 |
| RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | TIMEOUT | 281.84 |
| RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | TIMEOUT | 258.04 |
+---------------+-------------------------------------------------+---------+--------+
```

Note that the RZ_A1H results are due to an old revision of the hardware in the test system:
```
edgt: test case report:
| target     | platform_name | test suite                                      | test case                | passed | failed | result | elapsed_time (sec) |
|------------|---------------|-------------------------------------------------|--------------------------|--------|--------|--------|--------------------|
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | Connect to Ethernet      | 2      | 0      | OK     | 6.05               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | Format FAT               | 1      | 0      | OK     | 0.33               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | Initialize SD+FAT        | 2      | 0      | OK     | 0.03               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | Initialize Simple PDMC   | 2      | 0      | OK     | 2.2                |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | Pelion Bootstrap & Reg.  | 1      | 0      | OK     | 8.94               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | Pelion Directory         | 1      | 0      | OK     | 1.2                |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | Pelion Re-register       | 1      | 0      | OK     | 3.73               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | Post-reset Identity      | 1      | 0      | OK     | 0.12               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | Resource LwM2M GET       | 1      | 0      | OK     | 1.24               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | Resource LwM2M POST      | 1      | 0      | OK     | 0.78               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | Resource LwM2M PUT       | 1      | 0      | OK     | 1.22               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-connect | Resource LwM2M SET       | 1      | 0      | OK     | 0.56               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | Connect to Ethernet      | 2      | 0      | OK     | 8.55               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | Format FAT               | 1      | 0      | OK     | 0.29               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | Initialize SD+FAT        | 2      | 0      | OK     | 0.06               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | Initialize Simple PDMC   | 2      | 0      | OK     | 2.21               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | Pelion Bootstrap & Reg.  | 1      | 0      | OK     | 8.93               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | Pelion Directory         | 1      | 0      | OK     | 1.18               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | Pelion Firmware Download | 1      | 0      | OK     | 150.38             |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | Pelion Firmware Prepare  | 1      | 0      | OK     | 0.6                |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | Pelion Firmware Update   | 1      | 0      | OK     | 71.2               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | Pelion Re-register       | 1      | 0      | OK     | 3.76               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | Post-update Erase        | 1      | 0      | OK     | 0.01               |
| RZ_A1H-ARM | RZ_A1H        | simple-mbed-cloud-client-tests-dev_mgmt-update  | Post-update Identity     | 1      | 0      | OK     | 0.13               |
mbedgt: test case results: 24 OK
mbedgt: completed in 403.83 sec
```

Pending investigation specifically for RZ_A1H revision C (with @toyowata) which shouldn't gate this PR.

**Comment by screamerbg** [comment]
Part 2:
```
+---------------------+-------------------------------------------------+-------------+---------+
| target              | test suite                                      | result      |    time |
+---------------------+-------------------------------------------------+-------------+---------+
| DISCO_F413ZH        | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   84.12 |
| DISCO_F413ZH        | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  174.45 |
| DISCO_F746NG        | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |  117.16 |
| DISCO_F746NG        | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  190.23 |
| DISCO_F769NI        | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   66.29 |
| DISCO_F769NI        | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  157.11 |
| DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   87.71 |
| DISCO_L475VG_IOT01A | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  172.67 |
| EFM32GG11_STK3701   | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   74.61 |
| EFM32GG11_STK3701   | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  146.55 |
| GR_LYCHEE           | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   87.98 |
| GR_LYCHEE           | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |   279.3 |
| K64F                | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   90.14 |
| K64F                | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  173.66 |
| K66F                | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   82.72 |
| K66F                | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  167.17 |
| MTB_MXCHIP_EMW3166  | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |  103.15 |
| MTB_MXCHIP_EMW3166  | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |   238.1 |
| MTB_USI_WM_BN_BM_22 | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |  110.54 |
| MTB_USI_WM_BN_BM_22 | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  278.89 |
| NUCLEO_F207ZG       | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   73.08 |
| NUCLEO_F207ZG       | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  156.68 |
| NUCLEO_F429ZI       | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   79.24 |
| NUCLEO_F429ZI       | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  163.08 |
| NUCLEO_F746ZG       | simple-mbed-cloud-client-tests-dev_mgmt-connect | SYNC_FAILED |   51.63 |
| NUCLEO_F746ZG       | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  145.69 |
| NUCLEO_F767ZI       | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   72.32 |
| NUCLEO_F767ZI       | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  147.24 |
| NUMAKER_IOT_M487    | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   70.15 |
| NUMAKER_IOT_M487    | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  169.82 |
| NUMAKER_PFM_M487    | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   72.26 |
| NUMAKER_PFM_M487    | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  139.28 |
| NUMAKER_PFM_NUC472  | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |  147.48 |
| NUMAKER_PFM_NUC472  | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  235.16 |
| SDT64B              | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  191.98 |
| SDT64B              | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |   91.92 |
| UBLOX_C030_U201     | simple-mbed-cloud-client-tests-dev_mgmt-connect | TIMEOUT     |   270.4 |
| UBLOX_C030_U201     | simple-mbed-cloud-client-tests-dev_mgmt-update  | TIMEOUT     | 1829.61 |
| UBLOX_EVK_ODIN_W2   | simple-mbed-cloud-client-tests-dev_mgmt-connect | OK          |  165.17 |
| UBLOX_EVK_ODIN_W2   | simple-mbed-cloud-client-tests-dev_mgmt-update  | OK          |  484.51 |
+---------------------+-------------------------------------------------+-------------+---------+
```

Not that the UBLOX_C030_U201 reported errors are because we ran out of data

**Comment by screamerbg** [comment]
Bump @MarceloSalazar  :)

**Comment by MarceloSalazar** [comment]
Great work!

**Pull request merged**
